name: game-items-api
description: Game Items API with Convex Integration

services:
  convex-backend:
    image: ghcr.io/get-convex/convex-backend:5143fec81f146ca67495c12c6b7a15c5802c37e2
    ports:
      - "3210:3210"
      - "3211:3211"
    environment:
      - INSTANCE_NAME=game-items-api
      - INSTANCE_SECRET=${INSTANCE_SECRET}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN}
      - RUST_LOG=info
      - DISABLE_BEACON=true
      - REDACT_LOGS_TO_CLIENT=false
      - ACTIONS_USER_TIMEOUT_SECS=300
    volumes:
      - convex-data:/convex/data
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 5s
      timeout: 3s
      retries: 3

  convex-dashboard:
    image: ghcr.io/get-convex/convex-dashboard:5143fec81f146ca67495c12c6b7a15c5802c37e2
    ports:
      - "6791:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL}
    depends_on:
      convex-backend:
        condition: service_healthy

volumes:
  convex-data:
    driver: local

env:
  - INSTANCE_SECRET
  - NEXT_PUBLIC_DEPLOYMENT_URL
  - CONVEX_CLOUD_ORIGIN
  - CONVEX_SITE_ORIGIN 